### ISSUE TITLE
Unable to Load Dynamic Virtual Channel DLL in Microsoft Remote Desktop Application

### ISSUE THREAD

**Issue by hanexthink** [earthquake/UniversalDVC#8]
We are experiencing an issue where the dynamic virtual channel (DVC) DLL cannot be loaded when using the Microsoft Remote Desktop application downloaded from the Microsoft Store.

1. Download and install the Microsoft Remote Desktop application from the Microsoft Store.
2. Run the same steps mentioned in the GitHub repo  
3. Make a remote desktop connection using the  the Microsoft Remote Desktop application from the Microsoft Store.

**Comment by earthquake** [comment]
Hi @hanexthink,

Feel free to include technical details into this thread including your results on inspecting the loading with procmon. I have a feeling that this might come from that the dll is not signed, therefore the Microsoft Store application will not load it. If that is the case, this won't be resolved.

**Comment by hanexthink** [comment]
Hi @earthquake,
Thanks for your prompt reply, please refer to the following.
https://github.com/nccgroup/SocksOverRDP/issues/15#issuecomment-2213927494
Best HA

**Comment by earthquake** [comment]
Thanks again!
